In [1]:
a=2
b=3
a+b

5

Lição 1: Ambientando-se ao Python
\begin{equation}
c=a+b
\end{equation}

In [2]:
d="Bolsonaro"
d[0]

'B'

In [3]:
1/2

0

In [4]:
1.0/2.0


0.5

In [5]:
a=[1,9,25,34,17]
a

[1, 9, 25, 34, 17]

In [6]:
type(a)

list

In [7]:
b=[1.3,2.6,5.8,23.43]


In [8]:
a+b

[1, 9, 25, 34, 17, 1.3, 2.6, 5.8, 23.43]

In [9]:
a=0.356
type(a)

float

In [23]:
import numpy as np


In [24]:
a=numpy.array([0,1,2])
a
type(a)

numpy.ndarray

In [12]:
b=numpy.array([4,5,6])
b
type(b)

numpy.ndarray

In [13]:
a+b-a

array([4, 5, 6])

In [14]:
a+b

array([4, 6, 8])

In [15]:
A=numpy.array([[0,1,2],[2,3,4],[4,5,6]])
A

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [16]:
a.size

3

In [17]:
A.size

9

In [18]:
A.shape

(3L, 3L)

In [19]:
a.shape

(3L,)

In [20]:
A[2,1]

5

In [21]:
a

array([0, 1, 2])

In [22]:
a

array([0, 1, 2])

In [26]:
B=numpy.array([[5.5,6.5,7.5,8.5,9.5],[0.5,1.5,2.5],[0.22,1.34],[0,126]])
B

array([list([5.5, 6.5, 7.5, 8.5, 9.5]), list([0.5, 1.5, 2.5]),
       list([0.22, 1.34]), list([0, 126])], dtype=object)

In [27]:
B=numpy.array([[0.22,22,1.22],[0,5,5.5],[127,0,-0.23]])
B

array([[  0.22,  22.  ,   1.22],
       [  0.  ,   5.  ,   5.5 ],
       [127.  ,   0.  ,  -0.23]])

In [29]:
u=A+B
u

array([[  0.22,  23.  ,   3.22],
       [  2.  ,   8.  ,   9.5 ],
       [131.  ,   5.  ,   5.77]])

In [30]:
f=numpy.linalg.inv(B)
f

array([[-7.88100532e-05,  3.46764234e-04,  7.87415227e-03],
       [ 4.78685410e-02, -1.06215804e-02, -8.29218820e-05],
       [-4.35168554e-02,  1.91474164e-01,  7.53835291e-05]])

In [31]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])